server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health, info, bus, refresh